import { Colors, FontFamily, Shadow } from '@/constants/brand';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeRoot: {
    flex: 1,
    backgroundColor: Colors.creamLite,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(63, 3, 11, 0.08)',
    backgroundColor: Colors.white,
  },
  barCircleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(63, 3, 11, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  barTitleCenter: {
    alignItems: 'center',
    gap: 2,
  },
  barTitleText: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 18,
    color: Colors.ink,
    fontWeight: '700',
  },
  barSubText: {
    fontSize: 10.5,
    color: 'rgba(63, 3, 11, 0.45)',
    fontFamily: FontFamily.sansMedium,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(63, 3, 11, 0.05)',
  },
  stepItem: {
    alignItems: 'center',
    width: 90,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(63, 3, 11, 0.15)',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  stepCircleActive: {
    borderColor: Colors.oxblood,
    backgroundColor: Colors.oxblood,
  },
  stepCircleCompleted: {
    borderColor: Colors.green,
    backgroundColor: Colors.green,
  },
  stepNum: {
    fontFamily: FontFamily.sans,
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.45)',
  },
  stepNumActive: {
    color: Colors.white,
    fontWeight: '700',
  },
  stepLabel: {
    fontFamily: FontFamily.sans,
    fontSize: 10,
    color: 'rgba(63, 3, 11, 0.45)',
    fontWeight: '700',
  },
  stepLabelActive: {
    color: Colors.oxblood,
  },
  stepSubLabel: {
    fontSize: 8,
    color: 'rgba(63, 3, 11, 0.35)',
    fontFamily: FontFamily.sansMedium,
  },
  stepLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: 'rgba(63, 3, 11, 0.1)',
    marginHorizontal: -12,
    marginTop: -16,
  },
  stepLineActive: {
    backgroundColor: Colors.oxblood,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 56,
  },
  stepWrapper: {
    gap: 16,
  },
  formCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 16,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.06)',
    ...Shadow.card,
    gap: 14,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.oxblood,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 16,
    fontWeight: '700',
    color: Colors.ink,
  },
  cardSub: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.45)',
    fontFamily: FontFamily.sansMedium,
  },
  inputsStack: {
    gap: 12,
  },
  inputWrap: {
    gap: 6,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputLabel: {
    fontFamily: FontFamily.sans,
    fontSize: 11,
    color: Colors.roseDeep,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  counterText: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.35)',
    fontFamily: FontFamily.sansMedium,
  },
  textInput: {
    backgroundColor: 'rgba(63, 3, 11, 0.02)',
    borderRadius: 12,
    height: 46,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(63, 3, 11, 0.08)',
    fontSize: 14,
    color: Colors.ink,
    fontFamily: FontFamily.sansMedium,
  },
  rowInputs: {
    flexDirection: 'row',
    gap: 10,
  },
  rowFields: {
    flexDirection: 'row',
    gap: 12,
  },
  dropdownPicker: {
    backgroundColor: 'rgba(63, 3, 11, 0.02)',
    borderRadius: 12,
    height: 46,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(63, 3, 11, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pickerItem: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.1)',
    backgroundColor: Colors.white,
  },
  pickerItemActive: {
    backgroundColor: Colors.oxblood,
    borderColor: Colors.oxblood,
  },
  pickerItemText: {
    fontSize: 11,
    fontFamily: FontFamily.sansMedium,
    color: 'rgba(63, 3, 11, 0.6)',
  },
  pickerItemTextActive: {
    color: Colors.white,
    fontWeight: '700',
  },
  tipBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(243, 201, 105, 0.1)',
    borderRadius: 10,
    padding: 10,
    gap: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(243, 201, 105, 0.3)',
  },
  tipText: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.65)',
    fontFamily: FontFamily.sansMedium,
    flex: 1,
  },
  optionalBadge: {
    backgroundColor: 'rgba(180, 106, 116, 0.12)',
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  optionalBadgeText: {
    fontSize: 9.5,
    color: Colors.roseDeep,
    fontFamily: FontFamily.sans,
    fontWeight: '700',
  },
  videoSelectedContainer: {
    gap: 10,
  },
  videoPreviewMedia: {
    position: 'relative',
    height: 180,
    borderRadius: 14,
    overflow: 'hidden',
  },
  videoPreviewImage: {
    width: '100%',
    height: '100%',
  },
  videoPreviewOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  videoPreviewPlayCircle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -20 }, { translateY: -20 }],
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoDurationLabel: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
    color: Colors.white,
    fontSize: 10,
    fontFamily: FontFamily.sansMedium,
  },
  replaceVideoBtn: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: Colors.white,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 9,
    gap: 4,
    ...Shadow.card,
  },
  replaceVideoText: {
    fontSize: 10.5,
    fontFamily: FontFamily.sans,
    color: Colors.oxblood,
    fontWeight: '700',
  },
  videoFootnote: {
    fontSize: 10,
    color: 'rgba(63, 3, 11, 0.4)',
    fontFamily: FontFamily.sansMedium,
    textAlign: 'center',
  },
  dashedUploadBox: {
    height: 120,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(63, 3, 11, 0.2)',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  uploadBoxTitle: {
    fontSize: 13.5,
    fontFamily: FontFamily.sans,
    color: Colors.oxblood,
  },
  uploadBoxSub: {
    fontSize: 10,
    color: 'rgba(63, 3, 11, 0.4)',
    fontFamily: FontFamily.sansMedium,
  },
  textAreaInput: {
    backgroundColor: 'rgba(63, 3, 11, 0.02)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(63, 3, 11, 0.08)',
    padding: 12,
    fontSize: 14.5,
    color: Colors.ink,
    fontFamily: FontFamily.sansMedium,
    height: 100,
    textAlignVertical: 'top',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(180, 106, 116, 0.1)',
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 9,
    gap: 6,
  },
  tagPillText: {
    fontSize: 11.5,
    color: Colors.roseDeep,
    fontFamily: FontFamily.sansMedium,
    fontWeight: '600',
  },
  tagPillClose: {
    padding: 2,
  },
  tagAddBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(63, 3, 11, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagInputWrapper: {
    borderWidth: 1,
    borderColor: 'rgba(63, 3, 11, 0.15)',
    borderRadius: 8,
    paddingHorizontal: 8,
    backgroundColor: Colors.white,
    height: 28,
    justifyContent: 'center',
  },
  tagInputInline: {
    fontSize: 11,
    fontFamily: FontFamily.sansMedium,
    color: Colors.ink,
    width: 80,
    padding: 0,
  },
  continueBtn: {
    backgroundColor: Colors.oxblood,
    borderRadius: 14,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
    ...Shadow.button,
  },
  continueBtnText: {
    fontFamily: FontFamily.sans,
    fontSize: 13.5,
    color: Colors.white,
    fontWeight: '700',
  },

  // Step 2 Media layout
  sectionFormLabel: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 15.5,
    fontWeight: '700',
    color: Colors.ink,
  },
  sectionFormSub: {
    fontSize: 11.5,
    color: 'rgba(63, 3, 11, 0.45)',
    fontFamily: FontFamily.sansMedium,
    marginBottom: 4,
  },
  mediaDetailsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(63, 3, 11, 0.02)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.06)',
    gap: 12,
  },
  mediaDetailsLeft: {
    position: 'relative',
    width: 64,
    height: 74,
    borderRadius: 10,
    overflow: 'hidden',
  },
  mediaThumbImage: {
    width: '100%',
    height: '100%',
  },
  mediaThumbOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  mediaThumbPlayCircle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -10 }, { translateY: -10 }],
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaThumbDuration: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 3,
    paddingVertical: 1,
    paddingHorizontal: 3,
    color: Colors.white,
    fontSize: 7.5,
    fontWeight: '700',
  },
  mediaDetailsRight: {
    flex: 1,
    justifyContent: 'center',
    gap: 3,
  },
  mediaFilename: {
    fontSize: 13,
    fontFamily: FontFamily.sansMedium,
    color: Colors.ink,
    fontWeight: '700',
    flex: 1,
  },
  mediaFilesize: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.4)',
    fontFamily: FontFamily.sansMedium,
  },
  replaceVideoTextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  replaceVideoTextBtnLabel: {
    fontSize: 11,
    fontFamily: FontFamily.sans,
    color: Colors.roseDeep,
    fontWeight: '700',
  },
  framesScroll: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 4,
  },
  frameCard: {
    position: 'relative',
    width: 64,
    height: 64,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  frameCardActive: {
    borderColor: Colors.oxblood,
  },
  frameImage: {
    width: '100%',
    height: '100%',
  },
  frameChecked: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.oxblood,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashedFrameUpload: {
    width: 64,
    height: 64,
    borderRadius: 10,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(63, 3, 11, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  frameUploadText: {
    fontSize: 7.5,
    fontFamily: FontFamily.sans,
    fontWeight: '700',
    color: Colors.roseDeep,
  },
  suggestedPointsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 0.5,
    borderColor: 'rgba(180, 106, 116, 0.3)',
    backgroundColor: 'rgba(180, 106, 116, 0.05)',
  },
  suggestedText: {
    fontSize: 10.5,
    color: Colors.roseDeep,
    fontFamily: FontFamily.sans,
    fontWeight: '700',
  },
  deliverablesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  delivPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(42, 122, 90, 0.08)',
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 9,
    gap: 6,
  },
  delivPillText: {
    fontSize: 11.5,
    color: Colors.green,
    fontFamily: FontFamily.sansMedium,
    fontWeight: '600',
  },
  delivPillClose: {
    padding: 2,
  },
  delivAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(63, 3, 11, 0.3)',
    paddingHorizontal: 10,
    gap: 4,
  },
  delivAddText: {
    fontSize: 11,
    fontFamily: FontFamily.sansMedium,
    color: Colors.oxblood,
  },
  wizardFooterRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
  },
  wizardBackBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.oxblood,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.white,
  },
  wizardBackText: {
    fontFamily: FontFamily.sans,
    fontSize: 13.5,
    color: Colors.oxblood,
    fontWeight: '700',
  },
  wizardContinueBtn: {
    flex: 2,
    height: 48,
    backgroundColor: Colors.oxblood,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    ...Shadow.button,
  },
  wizardContinueText: {
    fontFamily: FontFamily.sans,
    fontSize: 13.5,
    color: Colors.white,
    fontWeight: '700',
  },

  // Step 3 Review & Publish
  sparkleBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(180, 106, 116, 0.08)',
    borderRadius: 14,
    padding: 12,
    gap: 12,
    borderWidth: 0.5,
    borderColor: 'rgba(180, 106, 116, 0.15)',
  },
  sparkleIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(180, 106, 116, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sparkleTitle: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 13.5,
    fontWeight: '700',
    color: Colors.roseDeep,
  },
  sparkleMessage: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.6)',
    fontFamily: FontFamily.sansMedium,
  },
  reviewLayout: {
    flexDirection: 'row',
    gap: 14,
    flexWrap: 'wrap',
  },
  reviewMain: {
    flex: 1.5,
    minWidth: 280,
    gap: 14,
  },
  reviewAside: {
    flex: 1,
    minWidth: 220,
    gap: 14,
  },
  reviewSecTitle: {
    fontSize: 11,
    fontFamily: FontFamily.sans,
    color: Colors.roseDeep,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  reviewPreviewCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.08)',
    ...Shadow.card,
  },
  reviewThumbContainer: {
    position: 'relative',
    height: 120,
  },
  reviewThumb: {
    width: '100%',
    height: '100%',
  },
  reviewThumbOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.12)',
  },
  reviewThumbPlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -15 }, { translateY: -15 }],
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewThumbDur: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 4,
    paddingVertical: 1,
    paddingHorizontal: 4,
    color: Colors.white,
    fontSize: 8.5,
    fontWeight: '700',
  },
  reviewCardBody: {
    padding: 10,
    gap: 6,
  },
  reviewCardTitle: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 13.5,
    fontWeight: '700',
    color: Colors.ink,
  },
  reviewDataCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.06)',
    ...Shadow.card,
    gap: 10,
  },
  reviewCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewDataTitle: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 14.5,
    fontWeight: '700',
    color: Colors.ink,
  },
  editLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  editLinkLabel: {
    fontSize: 11,
    fontFamily: FontFamily.sans,
    color: Colors.roseDeep,
    fontWeight: '700',
  },
  reviewDataGrid: {
    gap: 8,
  },
  reviewGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(63, 3, 11, 0.05)',
    paddingBottom: 6,
  },
  gridLabel: {
    fontSize: 11.5,
    color: 'rgba(63, 3, 11, 0.45)',
    fontFamily: FontFamily.sansMedium,
  },
  gridValue: {
    fontSize: 11.5,
    color: Colors.ink,
    fontFamily: FontFamily.sansMedium,
    fontWeight: '700',
  },
  reviewDescText: {
    fontSize: 12.5,
    lineHeight: 18,
    color: 'rgba(63, 3, 11, 0.7)',
    fontFamily: FontFamily.sansMedium,
  },
  deliverablesList: {
    gap: 6,
  },
  deliverableItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  greenCheck: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  delLabelText: {
    fontSize: 12,
    color: Colors.ink,
    fontFamily: FontFamily.sansMedium,
  },
  asideCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.06)',
    ...Shadow.card,
    gap: 8,
  },
  asideTitle: {
    fontFamily: FontFamily.sansMedium,
    fontSize: 13.5,
    fontWeight: '700',
    color: Colors.ink,
    marginBottom: 2,
  },
  asideDivider: {
    height: 0.5,
    backgroundColor: 'rgba(63, 3, 11, 0.08)',
  },
  asideRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  asideLabel: {
    fontSize: 11.5,
    color: 'rgba(63, 3, 11, 0.45)',
    fontFamily: FontFamily.sansMedium,
  },
  asideVal: {
    fontSize: 11.5,
    color: Colors.ink,
    fontFamily: FontFamily.sansMedium,
    fontWeight: '700',
  },
  highlightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 1,
  },
  highlightText: {
    fontSize: 11.5,
    color: 'rgba(63, 3, 11, 0.75)',
    fontFamily: FontFamily.sansMedium,
  },
  tipCheck: {
    fontSize: 11.5,
    color: 'rgba(63, 3, 11, 0.7)',
    fontFamily: FontFamily.sansMedium,
    paddingVertical: 1,
  },
  controlSubText: {
    fontSize: 10.5,
    color: 'rgba(63, 3, 11, 0.5)',
    fontFamily: FontFamily.sansMedium,
    lineHeight: 14,
  },
  confirmCheckboxRow: {
    flexDirection: 'row',
    padding: 10,
    gap: 10,
    alignItems: 'flex-start',
    backgroundColor: 'rgba(63, 3, 11, 0.02)',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: 'rgba(63, 3, 11, 0.08)',
    marginTop: 6,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: 'rgba(63, 3, 11, 0.3)',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: Colors.oxblood,
    borderColor: Colors.oxblood,
  },
  confirmLabel: {
    fontSize: 11,
    color: 'rgba(63, 3, 11, 0.65)',
    fontFamily: FontFamily.sansMedium,
    flex: 1,
    lineHeight: 16,
  },
  tagsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  platformBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(180, 106, 116, 0.15)',
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
    gap: 4,
  },
  platformText: {
    fontSize: 9.5,
    color: Colors.roseDeep,
    fontFamily: FontFamily.sansMedium,
    fontWeight: '600',
  },
  categoryBadge: {
    backgroundColor: 'rgba(63, 3, 11, 0.05)',
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  categoryText: {
    fontSize: 9.5,
    color: 'rgba(63, 3, 11, 0.6)',
    fontFamily: FontFamily.sansMedium,
    fontWeight: '600',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  ratingText: {
    fontSize: 10,
    color: 'rgba(63, 3, 11, 0.6)',
    fontFamily: FontFamily.sansMedium,
    marginLeft: 4,
  },
  loadingFramesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    height: 64,
  },
  loadingFramesText: {
    fontSize: 12,
    color: 'rgba(63, 3, 11, 0.5)',
    fontFamily: FontFamily.sansMedium,
  },
  skeletonFrameCard: {
    backgroundColor: 'rgba(63, 3, 11, 0.04)',
    borderColor: 'rgba(63, 3, 11, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
